# Generated by Django 4.1.2 on 2022-11-05 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finnhub_integration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finnhubsupportedexchanges',
            name='exchange_open_time',
        ),
        migrations.AddField(
            model_name='finnhubsupportedexchanges',
            name='exchange_country',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
