# Generated by Django 4.1.2 on 2022-11-05 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finnhub_integration', '0002_remove_finnhubsupportedexchanges_exchange_open_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinnhubSupportedStockSymbols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol_currency', models.CharField(max_length=100, null=True)),
                ('symbol_description', models.CharField(blank=True, max_length=200, null=True)),
                ('symbol_type', models.CharField(max_length=100, null=True)),
                ('symbol_display_sym', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('symbol_name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('symbol_exchange_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finnhub_integration.finnhubsupportedexchanges')),
            ],
        ),
    ]
